version: "3.3"
services:
  frontend:
    restart: always
    image: siredmar/elwainthesun:v0.3.0
    command: /controller serve -c /config.json
    ports:
      - "8080:8080"
    depends_on:
      - controller
    volumes:
      - /root/elwa/config.json:/config.json
    environment:
      LOG_LEVEL: info
  controller:
    restart: always
    image: siredmar/elwainthesun:v0.3.0
    command: /controller run -c /config.json
    volumes:
      - /root/elwa/config.json:/config.json
    environment:
      LOG_LEVEL: info
