package v1

type Power struct {
	ValidForMinutes       int `json:"validForMinutes"`
	Power                 int `json:"power"`
	PodPower              int `json:"pidPower"`
	TimeBoostOverride     int `json:"timeBoostOverride"`
	TimeBoostValue        int `json:"timeBoostValue"`
	LegionellaBoostBlock  int `json:"legionellaBoostBlock"`
	BatteryDischargeBlock int `json:"batteryDischargeBlock"`
}

type LiveData struct {
	Device          string `json:"device"`
	Fwversion       string `json:"fwversion"`
	Psversion       string `json:"psversion"`
	Coversion       string `json:"coversion"`
	Fsetup          int    `json:"fsetup"`
	P1S             int    `json:"p1_s"`
	P1V             string `json:"p1_v"`
	P2S             int    `json:"p2_s"`
	P2V             string `json:"p2_v"`
	PCoS            int    `json:"p_co_s"`
	PCoV            string `json:"p_co_v"`
	PPsS            int    `json:"p_ps_s"`
	PPsV            string `json:"p_ps_v"`
	PowerSystem     any    `json:"power_system"`
	ScreenModeFlag  int    `json:"screen_mode_flag"`
	PowerElwa2      int    `json:"power_elwa2"`
	PowerSolar      int    `json:"power_solar"`
	PowerGrid       int    `json:"power_grid"`
	Power1Solar     int    `json:"power1_solar"`
	Power1Grid      int    `json:"power1_grid"`
	Power2Solar     int    `json:"power2_solar"`
	Power2Grid      int    `json:"power2_grid"`
	Power3Solar     int    `json:"power3_solar"`
	Power3Grid      int    `json:"power3_grid"`
	Rel1Out         int    `json:"rel1_out"`
	RelSelv         int    `json:"rel_selv"`
	PowerNominal    int    `json:"power_nominal"`
	PowerMax        int    `json:"power_max"`
	Temp1           int    `json:"temp1"`
	Temp2           int    `json:"temp2"`
	Boostactive     int    `json:"boostactive"`
	Legboostnext    string `json:"legboostnext"`
	Date            string `json:"date"`
	Loctime         string `json:"loctime"`
	Unixtime        int    `json:"unixtime"`
	Uptime          int    `json:"uptime"`
	Ctrlstate       string `json:"ctrlstate"`
	Blockactive     int    `json:"blockactive"`
	Meter1ID        any    `json:"meter1_id"`
	Meter1IP        string `json:"meter1_ip"`
	Meter2ID        any    `json:"meter2_id"`
	Meter2IP        string `json:"meter2_ip"`
	Meter3ID        any    `json:"meter3_id"`
	Meter3IP        string `json:"meter3_ip"`
	Meter4ID        any    `json:"meter4_id"`
	Meter4IP        string `json:"meter4_ip"`
	Meter5ID        any    `json:"meter5_id"`
	Meter5IP        string `json:"meter5_ip"`
	Meter6ID        any    `json:"meter6_id"`
	Meter6IP        string `json:"meter6_ip"`
	MeterSs         any    `json:"meter_ss"`
	MeterSsid       string `json:"meter_ssid"`
	Surplus         any    `json:"surplus"`
	M0Sum           any    `json:"m0sum"`
	M0L1            any    `json:"m0l1"`
	M0L2            any    `json:"m0l2"`
	M0L3            any    `json:"m0l3"`
	M0Bat           any    `json:"m0bat"`
	M1Sum           any    `json:"m1sum"`
	M1L1            any    `json:"m1l1"`
	M1L2            any    `json:"m1l2"`
	M1L3            any    `json:"m1l3"`
	M1Devstate      any    `json:"m1devstate"`
	M2Sum           any    `json:"m2sum"`
	M2L1            any    `json:"m2l1"`
	M2L2            any    `json:"m2l2"`
	M2L3            any    `json:"m2l3"`
	M2Soc           any    `json:"m2soc"`
	M2State         any    `json:"m2state"`
	M2Devstate      any    `json:"m2devstate"`
	M3Sum           any    `json:"m3sum"`
	M3L1            any    `json:"m3l1"`
	M3L2            any    `json:"m3l2"`
	M3L3            any    `json:"m3l3"`
	M3Soc           any    `json:"m3soc"`
	M3Devstate      any    `json:"m3devstate"`
	M4Sum           any    `json:"m4sum"`
	M4L1            any    `json:"m4l1"`
	M4L2            any    `json:"m4l2"`
	M4L3            any    `json:"m4l3"`
	M4Devstate      any    `json:"m4devstate"`
	Batblockstate   any    `json:"batblockstate"`
	Ecarstate       string `json:"ecarstate"`
	Ecarboostctr    any    `json:"ecarboostctr"`
	Mss2            string `json:"mss2"`
	Mss3            string `json:"mss3"`
	Mss4            string `json:"mss4"`
	Mss5            string `json:"mss5"`
	Mss6            string `json:"mss6"`
	Mss7            string `json:"mss7"`
	Mss8            string `json:"mss8"`
	Mss9            string `json:"mss9"`
	Mss10           string `json:"mss10"`
	Mss11           string `json:"mss11"`
	VoltMains       int    `json:"volt_mains"`
	VoltAux         int    `json:"volt_aux"`
	Freq            int    `json:"freq"`
	TempPs          int    `json:"temp_ps"`
	FanSpeed        int    `json:"fan_speed"`
	PsState         int    `json:"ps_state"`
	CtrlErrors      int    `json:"ctrl_errors"`
	Warnings        int    `json:"warnings"`
	Fwversionlatest string `json:"fwversionlatest"`
	Coversionlatest string `json:"coversionlatest"`
	Psversionlatest string `json:"psversionlatest"`
	UpdState        int    `json:"upd_state"`
	PsUpdState      int    `json:"ps_upd_state"`
	CoUpdState      int    `json:"co_upd_state"`
	CurEthMode      int    `json:"cur_eth_mode"`
	WifiSignal      int    `json:"wifi_signal"`
	WifiList        []struct {
		Ssid   string `json:"ssid"`
		Signal int    `json:"signal"`
	} `json:"wifi_list"`
	CurIP      string `json:"cur_ip"`
	CurSn      string `json:"cur_sn"`
	CurGw      string `json:"cur_gw"`
	CurDNS     string `json:"cur_dns"`
	Cloudstate int    `json:"cloudstate"`
	DebugIP    string `json:"debug_ip"`
}
